name: platform_os
description: It also supports the web with packages that return widgets depending on the platform OS.
version: 1.0.2
repository: https://github.com/minhuits/platform_os

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
